# Generated by Django 4.2 on 2023-04-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('cohort', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=11)),
            ],
        ),
    ]
